#include "mainwindow.h"
#include "ui_mainwindow.h"
#include "client.h"
#include <QMessageBox>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);
}

MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow::on_btnAjouter_clicked()
{
    int autoGeneratedID = 1; // Remplacez ceci par votre logique d'auto-génération
    QString nom = ui->lineEdit_nom->text();
    QString prenom = ui->lineEdit_prenom->text();
    QString tel = ui->lineEdit_tel->text();
    QString email = ui->lineEdit_email->text();
    QString adresse = ui->lineEdit_adresse->text(); // Correction ici
    QString type = ui->lineEdit_type->text(); // Correction ici

    if (nom.isEmpty() || prenom.isEmpty() || tel.isEmpty() || email.isEmpty() || adresse.isEmpty() || type.isEmpty()) {
        QMessageBox::warning(this, "Champs vides", "Veuillez remplir tous les champs");
        return;
    }

    Client C(autoGeneratedID, nom, prenom, tel, email, adresse, type);
    // Ajoutez ici votre logique d'ajout en base de données
}

void MainWindow::on_btnsupprimer_clicked()
{
    int id = ui->lineEdit_id->text().toInt();
    Client C;
    bool success = C.supprimer(id);

    if (success) {
        QMessageBox::information(this, "Suppression", "Client supprimé avec succès");
    } else {
        QMessageBox::warning(this, "Erreur", "Suppression échouée");
    }
}

void MainWindow::modifierCellule(const QModelIndex &index)
{
    if (!index.isValid())
        return;

    QString newValue = index.data().toString();
    QString oldValue = ""; // Remplacez par l'ancienne valeur si nécessaire

    if (!newValue.isEmpty() && newValue != oldValue) {
        // Logique de mise à jour ici
    }
}
void MainWindow::on_annulerEvent_clicked() {
    // Réinitialiser les champs du formulaire
    ui->lineEdit_nom->clear();
    ui->lineEdit_prenom->clear();
    ui->lineEdit_tel->clear();
    ui->lineEdit_email->clear();
    ui->lineEdit_adresse->clear();
    ui->lineEdit_type->clear();


    // Optionnel : afficher un message
    QMessageBox::information(this, "Annulation", "Les champs ont été réinitialisés.");
}
