#include "mainwindow.h"
#include "architecte.h"
#include "./ui_mainwindow.h"
#include <QPushButton>
#include <QHBoxLayout>
#include <QWidget>
#include <QSqlQueryModel>
#include <QMessageBox>
#include <QInputDialog>
#include <QStandardItemModel>
#include <QSqlError>
#include <QRandomGenerator>
#include <QDateTime>
#include <QCryptographicHash>
#include <QLabel>
#include <QPdfWriter>
#include <QPainter>
#include <QSqlQuery>
#include <QFileDialog>
#include <QPageSize>
#include <QtCharts/QPieSeries>
#include <QtCharts/QChartView>
#include <QtCharts/QLineSeries>
#include <QtCharts/QChart>
#include <QtCharts>
#include <QSpacerItem>
#include <QSqlRecord>
#include "login.h"
#include <QIcon>
#include <QDialog>
#include <QFormLayout>
#include <QDialogButtonBox>
QT_USE_NAMESPACE
    //------------------------------------------------------------------------------------------------------------------------
    int MainWindow::generateAutoID() {
    int autoGeneratedID;
    Architecte A;
    do {
        int randomPart = QRandomGenerator::global()->bounded(1000, 10000);
        // Obtenir la partie basse du timestamp en millisecondes (modulo 10000 pour éviter un ID trop long)
        int timePart = QDateTime::currentMSecsSinceEpoch() % 10000;
        autoGeneratedID = (randomPart * 10) + (timePart % 10);
    } while (A.idExiste(autoGeneratedID));
    return autoGeneratedID;
}
//----------------------------------------------------------------------------------------------------------------------------

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent), ui(new Ui::MainWindow)
{
    ui->setupUi(this);
    Architecte::resetPresenceDaily();
   //  arduino = new Arduino(this);
    ui->lineEdit_motDePasse->setEchoMode(QLineEdit::Password);
    QPushButton *togglePasswordButton = new QPushButton(ui->lineEdit_motDePasse);
    togglePasswordButton->setCursor(Qt::PointingHandCursor);
    togglePasswordButton->setIcon(QIcon("C:/Users/Admin/Desktop/projet/dash/images/eye_closed.png"));
    togglePasswordButton->setStyleSheet("border: none; padding: 0px; background: transparent;");
    togglePasswordButton->setFixedSize(24, 24);
    togglePasswordButton->move(ui->lineEdit_motDePasse->width() - 30,
                               (ui->lineEdit_motDePasse->height() - 24) / 2);

    connect(togglePasswordButton, &QPushButton::clicked, [this, togglePasswordButton]() {
        if (ui->lineEdit_motDePasse->echoMode() == QLineEdit::Password) {
            ui->lineEdit_motDePasse->setEchoMode(QLineEdit::Normal);
            togglePasswordButton->setIcon(QIcon("C:/Users/Admin/Desktop/projet/dash/images/eye_open.png"));
        } else {
            ui->lineEdit_motDePasse->setEchoMode(QLineEdit::Password);
            togglePasswordButton->setIcon(QIcon("C:/Users/Admin/Desktop/projet/dash/images/eye_closed.png"));
        }
    });

    connect(ui->lineEdit_motDePasse, &QLineEdit::textChanged, [togglePasswordButton, this]() {
        togglePasswordButton->move(ui->lineEdit_motDePasse->width() - 30,
                                   (ui->lineEdit_motDePasse->height() - 24) / 2);
    });
    allModules = {
        ui->widgetArchitecte,
        ui->widgetClient,
        ui->widgetProjet,
        ui->widgetFormation,
        ui->widgetTache,
        ui->widgetRessources
    };
    ui->widgetSideBar->move(0, 0);
    ui->widgetSideBar->raise();
    ui->widgetSideBar->setFixedSize(ui->widgetSideBar->size());
    connect(ui->formationsBtn, &QPushButton::clicked, this, &MainWindow::on_formationsBtn_clicked);
    connect(ui->clientBtn, &QPushButton::clicked, this, &MainWindow::on_clientBtn_clicked);
    connect(ui->projetBtn, &QPushButton::clicked, this, &MainWindow::on_projetBtn_clicked);
    connect(ui->ressourcesBtn, &QPushButton::clicked, this, &MainWindow::on_ressourcesBtn_clicked);
    connect(ui->architecteBtn, &QPushButton::clicked, this, &MainWindow::on_architecteBtn_clicked);
    connect(ui->tacheBtn, &QPushButton::clicked, this, &MainWindow::on_tacheBtn_clicked);




    //--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    connect(ui->tableView, &QTableView::clicked, this, &MainWindow::modifierCellule);
    connect(ui->lineEdit_motDePasse, &QLineEdit::textChanged, this, [this](const QString &text) {
        verifierMotDePasse(text, ui->labelErreur); // Passez le label approprié
    });
    connect(ui->lineEdit_Rech, &QLineEdit::textChanged, this, &MainWindow::on_lineEdit_Rech_textChanged);
    connect(ui->exportBtn, &QPushButton::clicked, this, &MainWindow::exporterPDF);
    connect(ui->triCroissantButton, &QPushButton::clicked, this, &MainWindow::on_triCroissantButton_clicked);
    connect(ui->triDecroissantButton, &QPushButton::clicked, this, &MainWindow::on_triDecroissantButton_clicked);
    connect(ui->lineEdit_mail, &QLineEdit::textChanged, this, [this](const QString &text) {
        validateEmail(text, false);
    });
    setupValidation();
    afficherStatistiques();
    Architecte Etmp;
    ui->tableView->setModel(Etmp.afficher());
    this->setWindowTitle("ELICAR");
    QPixmap pixmap("C:/Users/Admin/Desktop/projet/dash/images/logo.png");
    if (!pixmap.isNull()) {
        QPixmap resizedPixmap = pixmap.scaled(128, 128, Qt::KeepAspectRatio, Qt::SmoothTransformation);
        this->setWindowIcon(QIcon(resizedPixmap));
    } else {
        qDebug() << "L'image du logo n'a pas pu être chargée!";
    }

}
//------------------------------------------------------------------------------------------------------------------------------------------------------------
MainWindow::~MainWindow()
{
    delete ui;
}
//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bool MainWindow::verifierMotDePasse(const QString &motDePasse, QLabel* labelErreur)
{
    static QRegularExpression regex("^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[^A-Za-z0-9\\s]).{8,}$");
    QRegularExpressionMatch match = regex.match(motDePasse);
    if (labelErreur) {
        if (match.hasMatch()) {
            labelErreur->setText("Mot de passe valide.");
            labelErreur->setStyleSheet("color: green;");
        } else {
            labelErreur->setText("Mot de passe:Min.8 caractères,1majuscule,<br>1 minuscule,1 chiffre,1 spécial.");
            labelErreur->setStyleSheet("color: red;");
        }
    }
    return match.hasMatch();
}
bool MainWindow::validateEmail(const QString &email, bool isModification)
{
    static QRegularExpression emailRegex("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");
    QRegularExpressionMatch match = emailRegex.match(email);
    bool valid = match.hasMatch();
    if (!isModification) {
        QLabel *labelEmailStatus = ui->labelEmailStatus;
        if (valid) {
            labelEmailStatus->setText("Email valide");
            labelEmailStatus->setStyleSheet("color: green; qproperty-alignment: AlignCenter;");
            labelEmailStatus->setAlignment(Qt::AlignCenter);
        } else {
            labelEmailStatus->setText("Email invalide");
            labelEmailStatus->setStyleSheet("color: red; qproperty-alignment: AlignCenter;");
            labelEmailStatus->setAlignment(Qt::AlignCenter);
        }
    }
    return valid;
}
bool MainWindow::verifierChampsLettresSeules(const QString &champ, QLabel *labelErreur)
{
    if (champ.length() < 3) {
        labelErreur->setText("Invalide: Min. 3 caractères");
        labelErreur->setStyleSheet("color: red; qproperty-alignment: AlignCenter;");
        return false;
    }
    // Expression régulière acceptant des lettres et des espaces
    static QRegularExpression regex("^[A-Za-z\\s]+$");
    // Déclarer QRegularExpressionMatch dans la même portée
    QRegularExpressionMatch match = regex.match(champ);
    if (match.hasMatch()) {
        labelErreur->setText("Valide");
        labelErreur->setStyleSheet("color: green; qproperty-alignment: AlignCenter;");
        return true;
    } else {
        labelErreur->setText("Invalide: uniquement des lettres et espaces.");
        labelErreur->setStyleSheet("color: red; qproperty-alignment: AlignCenter;");
        return false;
    }
}
//---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
void MainWindow::setupValidation()
{
    connect(ui->lineEdit_nom, &QLineEdit::textChanged, this, [this]() {
        verifierChampsLettresSeules(ui->lineEdit_nom->text(), ui->labelNomErreur);
    });
    connect(ui->lineEdit_prenom, &QLineEdit::textChanged, this, [this]() {
        verifierChampsLettresSeules(ui->lineEdit_prenom->text(), ui->labelPrenomErreur);
    });
    connect(ui->lineEdit_response, &QLineEdit::textChanged, this, [this]() {
        verifierChampsLettresSeules(ui->lineEdit_response->text(), ui->labelReponseErreur);
    });
}
//----------------------CRUD AJOUTER---------------------------------------------------------------------------------------------------------------------------------------------------------------
void MainWindow::on_btnAjouter_clicked()
{
    int autoGeneratedID = generateAutoID();
    int heuresSupplementaires = 0;
    QString nom = ui->lineEdit_nom->text();
    QString prenom = ui->lineEdit_prenom->text();

    QString role = ui->comboBox_Role->currentText();
    QString reponse = ui->lineEdit_response->text();
    QString question = ui->comboBox_question->currentText();
    QString mail = ui->lineEdit_mail->text();
    QString motDePasse = ui->lineEdit_motDePasse->text();
    if (nom.isEmpty() || prenom.isEmpty() || mail.isEmpty() || role.isEmpty() ||
        motDePasse.isEmpty() || reponse.isEmpty())
    {
        QMessageBox::warning(this, "Champs vides", "Tous les champs doivent être remplis !");
        return;
    }
    if (!verifierChampsLettresSeules(nom, ui->labelNomErreur)) {
        QMessageBox::warning(this, "Nom invalide", "Le nom doit contenir uniquement des lettres et au moins 3 caractères.");
        return;
    }
    if (!verifierChampsLettresSeules(prenom, ui->labelPrenomErreur)) {
        QMessageBox::warning(this, "Prénom invalide", "Le nom doit contenir uniquement des lettres et au moins 3 caractères.");
        return;
    }

    if (!verifierChampsLettresSeules(reponse, ui->labelReponseErreur)) {
        QMessageBox::warning(this, "Réponse invalide", "Le nom doit contenir uniquement des lettres et au moins 3 caractères.");
        return;
    }
    if (!validateEmail(mail)) {
        QMessageBox::warning(this, "Email invalide", "L'adresse e-mail saisie est invalide.\nVeuillez respecter le format standard de l'email.");
        return;
    }
    if (!verifierMotDePasse(motDePasse)) {
        QMessageBox::warning(this, "Mot de passe invalide", "Le mot de passe doit respecter les critères");
        return;
    } else {
        motDePasse = hasherMotDePasse(motDePasse);
    }
    Architecte A(autoGeneratedID, nom, prenom, mail, role, motDePasse, question, reponse, heuresSupplementaires);
    bool test = A.ajouter();
    if (test) {
        qDebug() << "Ajout réussi";

        Architecte Etmp;
        ui->tableView->setModel(Etmp.afficher());
        afficherStatistiques();
        on_annulerEvent_clicked();

        QTimer::singleShot(100, this, [this]() {
            emit architectesUpdated();  // envoyer APRES 100 ms
        });



    }
}
//--------CRUD SUPPRIMER------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
void MainWindow::on_btnsupprimer_clicked()
{
    int id = ui->lineEdit_IDS->text().toInt();
    Architecte Etmp;
    if (!Etmp.idExiste(id))
    {
        QMessageBox::warning(this, "Erreur", "ID non trouvé !");
        ui->lineEdit_IDS->clear();
        return;
    }
    QString nom, prenom;
    Etmp.getNomPrenom(id, nom, prenom);
    QString confirmText = "ID: " + QString::number(id) + "\nNom: " + nom + "\nPrénom: " + prenom + "\nSouhaitez-vous vraiment supprimer cet élément ?";
    QMessageBox::StandardButton reply;
    reply = QMessageBox::question(this, "Confirmation", confirmText,
                                  QMessageBox::Yes | QMessageBox::No);
    if (reply == QMessageBox::Yes) {
        bool test = Etmp.supprimer(id);
        if (test)
        {
            qDebug() << "Suppression effectuée avec succès!";


            QSqlQueryModel *model = Etmp.afficher();
            ui->tableView->setModel(model);
              afficherStatistiques();
            QTimer::singleShot(100, this, [this]() {
                emit architectesUpdated();  // envoyer APRES 100 ms
            });



        }
        else
        {
            qDebug() << "Erreur: Suppression non effectuée.";
        }
    }
    else
    {
        QMessageBox::information(this, "Annulation", "La suppression a été annulée.");
    }
    ui->lineEdit_IDS->clear();
}
//----------------------------CRUD MODIFIER--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
void MainWindow::modifierCellule(const QModelIndex &index)
{
    QSqlQueryModel *model = qobject_cast<QSqlQueryModel *>(ui->tableView->model());

    if (!model) {
        qDebug() << "Le modèle n'est pas de type QSqlQueryModel.";
        return;
    }

    // Colonnes non modifiables
    if (index.column() == 0 || index.column() == 6 || index.column() == 7 || index.column() == 8) {
        QMessageBox::warning(this, tr("Modification non autorisée"), tr("Vous ne pouvez pas modifier cette colonne."));
        return;
    }

    QString columnName = model->headerData(index.column(), Qt::Horizontal).toString();
    QString newValue;
    bool inputOk = false;

    // Si colonne NOM ou PRÉNOM : demander du texte et valider
    if (columnName == "NOM" || columnName == "PRÉNOM") {
        newValue = QInputDialog::getText(this, tr("Modifier ") + columnName,
                                         tr("Nouvelle valeur :"), QLineEdit::Normal,
                                         model->data(index).toString(), &inputOk);
        if (inputOk && (!estTexteValide(newValue) || newValue.length() < 3)) {
            QMessageBox::warning(this, tr("Erreur de saisie"), tr("Le champ doit contenir uniquement des lettres et au moins 3 caractères."));
            return;
        }

        QTimer::singleShot(100, this, [this]() {
            emit architectesUpdated();  // envoyer APRES 100 ms
        });


    }
    // Si colonne RÔLE : proposer une liste déroulante
    else if (columnName == "RÔLE") {
        QComboBox *roleComboBox = new QComboBox(this);
        roleComboBox->addItems({"Administrateur", "Responsable clients", "Responsable de projet", "Formateur", "Gestionnaire de Tâches", "Gestionnaire Ressources"});

        QDialog dialog(this);
        dialog.setWindowTitle(tr("Modifier le rôle"));
        QFormLayout form(&dialog);
        form.addRow(tr("Nouveau rôle:"), roleComboBox);

        QDialogButtonBox buttonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, Qt::Horizontal, &dialog);
        form.addRow(&buttonBox);

        connect(&buttonBox, &QDialogButtonBox::accepted, &dialog, &QDialog::accept);
        connect(&buttonBox, &QDialogButtonBox::rejected, &dialog, &QDialog::reject);

        if (dialog.exec() == QDialog::Accepted) {
            newValue = roleComboBox->currentText();
            inputOk = true;
        }
    }
    // Si colonne ETAT_PRESENCE : proposer A ou P
    else if (columnName == "ETAT_PRESENCE") {
        QStringList choix = {"A", "P"};
        newValue = QInputDialog::getItem(this, tr("Modifier l'état de présence"),
                                         tr("Nouvelle valeur (A ou P) :"),
                                         choix, 0, false, &inputOk);

        QTimer::singleShot(100, this, [this]() {
            emit architectesUpdated();  // envoyer APRES 100 ms
        });


    }
    else {
        // Sinon, modification libre pour d'autres colonnes
        newValue = QInputDialog::getText(this, tr("Modifier ") + columnName,
                                         tr("Nouvelle valeur :"), QLineEdit::Normal,
                                         model->data(index).toString(), &inputOk);
    }

    if (!inputOk) {
        return; // utilisateur a annulé
    }

    // Récupérer ID
    int id = model->data(model->index(index.row(), 0)).toInt();

    // Mettre à jour dans la base
    Architecte etmp;
    bool success = etmp.modifier(id, columnName, newValue);

    if (success) {
        // Mettre à jour la vue
        ui->tableView->setModel(etmp.afficher());
    } else {
        QMessageBox::warning(this, tr("Erreur de mise à jour"), tr("La mise à jour a échoué. Veuillez vérifier les données."));
    }
}

//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bool MainWindow::isValidColumn(const QString &columnName)
{
    QStringList validColumns = {"NOM", "PRÉNOM", "EMAIL", "RÔLE", "MOT_DE_PASSE", "NBR_HEURES_SUPPLEMENTAIRES", "ETAT_PRESENCE"};
    return validColumns.contains(columnName);
}
//--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bool MainWindow::isValidSupplementaryHours(const QString &value)
{
    bool isNumber;
    value.toInt(&isNumber);
    return isNumber;
}
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
QString MainWindow::hasherMotDePasse(const QString &motDePasse)
{
    QByteArray hash = QCryptographicHash::hash(motDePasse.toUtf8(), QCryptographicHash::Sha256);
    return hash.toBase64();
}
//--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
void MainWindow::on_annulerEvent_clicked()
{
    ui->lineEdit_nom->clear();
    ui->lineEdit_prenom->clear();
    ui->lineEdit_mail->clear();
    ui->lineEdit_motDePasse->clear();
    ui->lineEdit_response->clear();
    ui->labelErreur->clear();
    ui->labelNomErreur->clear();
    ui->labelPrenomErreur->clear();
    ui->labelRoleErreur->clear();
    ui->labelEmailStatus->clear();
    ui->labelReponseErreur->clear();
    ui->comboBox_question->setCurrentIndex(0);
    ui->comboBox_Role->setCurrentIndex(0);
}
bool MainWindow::estTexteValide(const QString &texte)
{
    if (texte.length() < 3) {
        return false;
    }
    static QRegularExpression regex("^[A-Za-z\\s]+$");
    return regex.match(texte).hasMatch();
}
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
void MainWindow::on_lineEdit_Rech_textChanged(const QString &text)
{
    Architecte A;
    QSqlQueryModel *model = A.rechercher(text);
    ui->tableView->setModel(model);

    if (model) {
        if (model->rowCount() == 0) {

            QStandardItemModel *emptyModel = new QStandardItemModel(1, model->columnCount(), this);
            // Copier les en-têtes
            for (int col = 0; col < model->columnCount(); ++col) {
                emptyModel->setHorizontalHeaderItem(col,
                                                    new QStandardItem(model->headerData(col, Qt::Horizontal).toString()));
            }

            QStandardItem *item = new QStandardItem("Architecte n'existe pas !");
            item->setForeground(Qt::red);
            item->setTextAlignment(Qt::AlignCenter);
            emptyModel->setItem(0, 0, item);
            ui->tableView->setModel(emptyModel);
            ui->tableView->setSpan(0, 0, 1, model->columnCount());
            for (int col = 0; col < model->columnCount(); ++col) {
                ui->tableView->horizontalHeader()->setSectionResizeMode(col, QHeaderView::Stretch);
            }
        } else {
            // Réinitialiser les fusions avant de changer le modèle
            ui->tableView->clearSpans();
            ui->tableView->setModel(model);
            // Réinitialiser les paramètres de redimensionnement
            ui->tableView->horizontalHeader()->setSectionResizeMode(QHeaderView::Interactive);
        }
    } else {
        QMessageBox::warning(this, "Erreur", "Une erreur s'est produite lors de la recherche.");
    }
}
//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
void MainWindow::exporterPDF()
{
    QString fileName = QFileDialog::getSaveFileName(this, "Exporter en PDF", "", "Fichiers PDF (*.pdf)");
    if (fileName.isEmpty()) {
        return;
    }

    Architecte architecte;
    QSqlQueryModel *model = architecte.afficher();
    if (!model) {
        QMessageBox::warning(this, "Erreur", "Impossible de récupérer les données.");
        return;
    }

    QPdfWriter writer(fileName);
    writer.setPageSize(QPageSize::A4);
    writer.setPageOrientation(QPageLayout::Landscape);
    writer.setResolution(120);
    QPainter painter(&writer);
    if (!painter.isActive()) {
        QMessageBox::warning(this, "Erreur", "Impossible de créer le PDF.");
        return;
    }

    const int margin = 30;
    const int titleHeight = 50;
    const int headerHeight = 40;
    const int rowHeight = 35;
    const int colCount = 6;
    int colWidths[colCount] = {210, 220, 220, 220, 220, 220};
    const int lineWidth = 1;


    int yPos = margin;
    int xPos = margin;
    // Polices
    QFont titleFont("Arial", 18, QFont::Bold);
    QFont headerFont("Arial", 10, QFont::Bold);
    QFont dataFont("Arial", 10);

    painter.setFont(titleFont);
    painter.drawText(xPos, yPos, writer.width() - 2*margin, titleHeight,
                     Qt::AlignCenter | Qt::AlignVCenter, "LISTE DES ARCHITECTES");
    yPos += titleHeight + 20;
    // Dessin des en-têtes
    painter.setFont(headerFont);
    painter.setPen(QPen(Qt::black, lineWidth));
    painter.setBrush(QColor(240, 240, 240));
    // Dessin du rectangle d'en-tête
    painter.drawRect(xPos, yPos, writer.width() - 2*margin, headerHeight);
    // Texte des en-têtes
    QString headers[colCount] = {"ID", "NOM", "PRÉNOM", "EMAIL", "RÔLE", "H. SUPPL."};
    int currentX = xPos;
    for (int col = 0; col < colCount; ++col) {
        Qt::Alignment align = (col == colCount-1) ? Qt::AlignCenter : Qt::AlignLeft;

        painter.drawText(currentX, yPos,
                         colWidths[col], headerHeight,
                         align | Qt::AlignVCenter, headers[col]);

        if (col < colCount - 1) {
            painter.drawLine(currentX + colWidths[col], yPos,
                             currentX + colWidths[col], yPos + headerHeight);
        }
        currentX += colWidths[col];
    }
    yPos += headerHeight;


    painter.setFont(dataFont);

    for (int row = 0; row < model->rowCount(); ++row) {
        // Alternance des couleurs de fond
        painter.setBrush(row % 2 ? Qt::white : QColor(248, 248, 248));
        painter.setPen(Qt::NoPen);
        painter.drawRect(xPos, yPos, writer.width() - 2*margin, rowHeight);


        painter.setPen(QPen(Qt::black, lineWidth));
        currentX = xPos;
        for (int col = 0; col < colCount; ++col) {
            QString text = model->data(model->index(row, col)).toString();

            if (col == colCount-1) {
                bool ok;
                int hours = text.toInt(&ok);
                text = ok ? QString::number(hours) : "0";
            }

            Qt::Alignment align = (col == colCount-1) ? Qt::AlignCenter : Qt::AlignLeft;

            painter.drawText(currentX, yPos,
                             colWidths[col], rowHeight,
                             align | Qt::AlignVCenter, text);

            if (col < colCount - 1) {
                painter.drawLine(currentX + colWidths[col], yPos,
                                 currentX + colWidths[col], yPos + rowHeight);
            }
            currentX += colWidths[col];
        }


        painter.drawLine(xPos, yPos, currentX, yPos);
        painter.drawLine(xPos, yPos + rowHeight, currentX, yPos + rowHeight);

        yPos += rowHeight;


        if (yPos > writer.height() - margin - rowHeight) {
            writer.newPage();
            yPos = margin;


            painter.setFont(headerFont);
            painter.setPen(QPen(Qt::black, lineWidth));
            painter.setBrush(QColor(240, 240, 240));
            painter.drawRect(xPos, yPos, writer.width() - 2*margin, headerHeight);

            currentX = xPos;
            for (int col = 0; col < colCount; ++col) {
                Qt::Alignment align = (col == colCount-1) ? Qt::AlignCenter : Qt::AlignLeft;
                painter.drawText(currentX, yPos,
                                 colWidths[col], headerHeight,
                                 align | Qt::AlignVCenter, headers[col]);

                if (col < colCount - 1) {
                    painter.drawLine(currentX + colWidths[col], yPos,
                                     currentX + colWidths[col], yPos + headerHeight);
                }
                currentX += colWidths[col];
            }
            yPos += headerHeight;
        }
    }
    painter.end();
    QMessageBox::information(this, "Exportation réussie", "Le fichier PDF a été exporté avec succès.");
}
//--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
void MainWindow::on_triCroissantButton_clicked()
{
    ui->lineEdit_Rech->clear();
    Architecte A;
    QSqlQueryModel *model = A.afficherAvecTri("NOM", true);
    ui->tableView->setModel(model);
}
void MainWindow::on_triDecroissantButton_clicked()
{
    ui->lineEdit_Rech->clear();
    Architecte A;
    QSqlQueryModel *model = A.afficherAvecTri("NOM", false);
    ui->tableView->setModel(model);
}
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
void MainWindow::afficherStatistiques() {

    QLayoutItem* child;
    while ((child = ui->statistiquesLayout->takeAt(0)) != nullptr) {
        if (child->widget()) {
            child->widget()->deleteLater();
        }
        delete child;
    }


    int plus50 = 0, moins20 = 0, entre20et50 = 0;
    QSqlQuery query("SELECT NBR_HEURES_SUPPLEMENTAIRES FROM ARCHITECTE");
    while (query.next()) {
        int heures = query.value(0).toInt();
        if (heures > 50) plus50++;
        else if (heures < 20) moins20++;
        else entre20et50++;
    }

    // Création du diagramme circulaire
    QPieSeries *series = new QPieSeries();


    int total = plus50 + moins20 + entre20et50;
    if (total == 0) {
        QLabel *noDataLabel = new QLabel("Aucune donnée disponible");
        noDataLabel->setAlignment(Qt::AlignCenter);
        ui->statistiquesLayout->addWidget(noDataLabel);

        return;
    }
    // Configuration des tranches avec les nouvelles couleurs
    if (plus50 > 0) {
        QPieSlice *slice = series->append("", plus50);
        slice->setColor(QColor(31, 78, 120)); // Bleu foncé
        slice->setLabel(QString("%1%").arg(QString::number((plus50 * 100.0 / total), 'f', 1)));
        slice->setLabelVisible(true);
        slice->setLabelPosition(QPieSlice::LabelOutside);
        slice->setProperty("legendText", "plus de 50 heures");
    }
    if (moins20 > 0) {
        QPieSlice *slice = series->append("", moins20);
        slice->setColor(QColor(238, 229, 211)); // Beige clair
        slice->setLabel(QString("%1%").arg(QString::number((moins20 * 100.0 / total), 'f', 1)));
        slice->setLabelVisible(true);
        slice->setLabelPosition(QPieSlice::LabelOutside);
        slice->setProperty("legendText", "moins de 20 heures");
    }
    if (entre20et50 > 0) {
        QPieSlice *slice = series->append("", entre20et50);
        slice->setColor(QColor(34, 45, 82)); // Bleu nuit
        slice->setLabel(QString("%1%").arg(QString::number((entre20et50 * 100.0 / total), 'f', 1)));
        slice->setLabelVisible(true);
        slice->setLabelPosition(QPieSlice::LabelOutside);
        slice->setProperty("legendText", "entre 20 et 50 heures");
    }


    // Configuration du graphique
    QChart *chart = new QChart();
    chart->addSeries(series);
    chart->setTitle("Statistiques sur les heures supplémentaires des architectes");
    // Style du titre
    chart->setTitleBrush(QBrush(Qt::black));
    QFont titleFont;
    titleFont.setBold(true);
    titleFont.setPointSize(9);
    chart->setTitleFont(titleFont);
    // Ajuster les marges pour décaler le titre
    chart->setMargins(QMargins(-10, 0, 0, 0));
    // Définir la couleur de fond
    chart->setBackgroundBrush(QBrush(QColor(224, 224, 224)));
    chart->setBackgroundVisible(true);
    // Configuration de la légende
    chart->legend()->setVisible(true);
    chart->legend()->setAlignment(Qt::AlignRight);
    chart->legend()->setBackgroundVisible(true);
    chart->legend()->setBrush(QBrush(QColor(224, 224, 224))); // Même fond que le graphique
    chart->setAnimationOptions(QChart::AllAnimations);
    // Personnalisation des libellés de la légende
    QList<QLegendMarker*> markers = chart->legend()->markers(series);
    for (int i = 0; i < markers.size(); ++i) {
        QPieSlice *slice = series->slices().at(i);
        markers.at(i)->setLabel(slice->property("legendText").toString());
    }
    // Création de la vue
    QChartView *chartView = new QChartView(chart);
    chartView->setRenderHint(QPainter::Antialiasing);
    chartView->setMinimumSize(300, 200);
    // Définir le fond du widget
    chartView->setBackgroundBrush(QBrush(QColor(224, 224, 224)));
    chartView->setAutoFillBackground(true);
    // Ajout au layout
    ui->statistiquesLayout->addWidget(chartView);
}
//--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
void MainWindow::switchWidget(QWidget* widgetToShow) {

    widgetToShow->setGeometry(this->rect());

    // Liste  widgets
    QList<QWidget*> mainWidgets = {
        ui->widgetArchitecte,
        ui->widgetRessources,
        ui->widgetTache,
        ui->widgetProjet,
        ui->widgetClient,
        ui->widgetFormation
    };


    for (QWidget* widget : mainWidgets) {
        widget->setVisible(widget == widgetToShow);
    }


    QString defaultStyle = "";
    QString activeStyle = "QPushButton { background-color: white; color: black; }";

    QList<QPushButton*> navButtons = {
        ui->architecteBtn,
        ui->ressourcesBtn,
        ui->tacheBtn,
        ui->projetBtn,
        ui->clientBtn,
        ui->formationsBtn
    };


    for (QPushButton* button : navButtons) {
        button->setStyleSheet(defaultStyle);
    }


    if (widgetToShow == ui->widgetArchitecte) {
        ui->architecteBtn->setStyleSheet(activeStyle);
    } else if (widgetToShow == ui->widgetRessources) {
        ui->ressourcesBtn->setStyleSheet(activeStyle);
    } else if (widgetToShow == ui->widgetTache) {
        ui->tacheBtn->setStyleSheet(activeStyle);
    } else if (widgetToShow == ui->widgetProjet) {
        ui->projetBtn->setStyleSheet(activeStyle);
    } else if (widgetToShow == ui->widgetClient) {
        ui->clientBtn->setStyleSheet(activeStyle);
    } else if (widgetToShow == ui->widgetFormation) {
        ui->formationsBtn->setStyleSheet(activeStyle);
    }
}
void MainWindow::on_clientBtn_clicked() {
    switchWidget(ui->widgetClient);
}
void MainWindow::on_architecteBtn_clicked() {
    switchWidget(ui->widgetArchitecte);
}
void MainWindow::on_ressourcesBtn_clicked() {
    switchWidget(ui->widgetRessources);
}

void MainWindow::on_tacheBtn_clicked() {
    switchWidget(ui->widgetTache);
}

void MainWindow::on_projetBtn_clicked() {
    switchWidget(ui->widgetProjet);
}
void MainWindow::on_formationsBtn_clicked()
{
    switchWidget(ui->widgetFormation);

}

void MainWindow::handleLoginSuccess(const QString &role) {
    qDebug() << "Role reçu:" << role;
    currentUserRole = role;
    setupPermissions();
    // setupPermissions();
    if (role == "Administrateur") {
        switchWidget(ui->widgetArchitecte);
    } else if (role == "Responsable clients") {
        switchWidget(ui->widgetClient);
    } else if (role == "Responsable de  projet") {
        switchWidget(ui->widgetProjet);
    } else if (role == "Formateur") {
        switchWidget(ui->widgetFormation);
    }
    else if (role == "Gestionnaire de Tâches") {
        switchWidget(ui->widgetTache);
    }
    else if (role == "Gestionnaire Ressources") {
        switchWidget(ui->widgetRessources);
    }

    this->show();
}

void MainWindow::setupPermissions() {

    QList<QPushButton*> navButtons = {
        ui->architecteBtn, ui->clientBtn, ui->projetBtn,
        ui->formationsBtn, ui->tacheBtn, ui->ressourcesBtn
    };

    foreach(QPushButton *btn, navButtons) {
        btn->setEnabled(true);
    }


    foreach(QWidget *module, allModules) {
        foreach(QWidget *child, module->findChildren<QWidget*>()) {
            if(currentUserRole != "Administrateur") {
                child->installEventFilter(this);
            }
        }
    }
}

bool MainWindow::isModuleAllowed(QWidget *module) {
    if(currentUserRole == "Administrateur") return true;
    if (module == ui->widgetArchitecte)
        return currentUserRole == "Administrateur";
    if (module == ui->widgetClient)
        return currentUserRole == "Responsable clients";
    if (module == ui->widgetFormation)
        return currentUserRole == "Formateur";
    if (module == ui->widgetProjet)
        return currentUserRole == "Responsable de  projet";
    if (module == ui->widgetRessources)
        return currentUserRole == "Gestionnaire Ressources";
    if (module == ui->widgetTache)
        return currentUserRole == "Gestionnaire de Tâches";

    return false;
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event) {
    if (currentUserRole == "Administrateur") return QMainWindow::eventFilter(obj, event);

    const auto type = event->type();
    QWidget* widget = qobject_cast<QWidget*>(obj);

    if ((type == QEvent::MouseButtonPress || type == QEvent::KeyPress) && widget) {
        if (QWidget* module = findParentModule(widget); module && !isModuleAllowed(module)) {
            QMessageBox::warning(this, "Accès refusé", "Vous n'avez pas les droits nécessaires !");
            return true;
        }
    }
    else if (type == QEvent::Enter && widget) {
        if (QWidget* module = findParentModule(widget); module && !isModuleAllowed(module)) {
            widget->setCursor(Qt::ForbiddenCursor);
        }
    }
    else if (type == QEvent::Leave && widget) {
        widget->unsetCursor();
    }

    return QMainWindow::eventFilter(obj, event);
}
QWidget* MainWindow::findParentModule(QWidget *child) {
    while (child && !allModules.contains(child)) {
        child = child->parentWidget();
    }
    return child;
}
void  MainWindow::on_btnDeconnecter_clicked()
{
    emit  logoutSuccess();
}
void MainWindow::refreshTable()
{
    Architecte Etmp;
    ui->tableView->setModel(Etmp.afficher());
}


