#include "mainwindow.h"
#include "architecte.h"
#include "./ui_mainwindow.h"
#include <QPushButton>
#include <QHBoxLayout>
#include <QWidget>
#include <QSqlQueryModel>
#include <QMessageBox>
#include <QInputDialog>
#include <QStandardItemModel>
#include <QSqlError>
#include <QRandomGenerator>
#include <QDateTime>
#include <QCryptographicHash>
#include <QLabel>



// Définition de la fonction generateAutoID dans le .cpp
int MainWindow::generateAutoID() {
    int autoGeneratedID;
    Architecte A;

    do {
        // Générer un entier aléatoire court (ex: entre 1000 et 9999)
        int randomPart = QRandomGenerator::global()->bounded(1000, 10000);

        // Obtenir la partie basse du timestamp en millisecondes (modulo 10000 pour éviter un ID trop long)
        int timePart = QDateTime::currentMSecsSinceEpoch() % 10000;

        // Combiner les deux parties
        autoGeneratedID = (randomPart * 10) + (timePart % 10);

    } while (A.idExiste(autoGeneratedID));  // Vérifier l'unicité

    return autoGeneratedID;  // Retourner un ID unique
}


MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent), ui(new Ui::MainWindow) // Initialisation du pointeur ui
{
    ui->setupUi(this);  // Mise en place de l'UI
    connect(ui->tableView, &QTableView::clicked, this, &MainWindow::modifierCellule);
  //  connect(ui->lineEdit_nom, &QLineEdit::textChanged, this, &MainWindow::verifierSaisie);
    connect(ui->lineEdit_motDePasse, &QLineEdit::textChanged, this, &MainWindow::verifierMotDePasse);
     connect(ui->lineEdit_mail, &QLineEdit::textChanged, this, &MainWindow::validateEmail);
      setupValidation();


    // Créer une instance de Architecte pour afficher les données
    Architecte Etmp;
    ui->tableView->setModel(Etmp.afficher());  // Afficher les données via la méthode afficher() de la classe Architecte

    this->setWindowTitle("ELICAR");

    // Charger et vérifier l'image de l'icône de l'application
    QPixmap pixmap("C:/Users/Admin/Desktop/projet/images/logo.png");
    if (!pixmap.isNull()) {
        QPixmap resizedPixmap = pixmap.scaled(128, 128, Qt::KeepAspectRatio, Qt::SmoothTransformation);
        this->setWindowIcon(QIcon(resizedPixmap));
    } else {
        qDebug() << "L'image du logo n'a pas pu être chargée!";
    }

    // Créer le modèle pour la QTableView
    QSqlQueryModel *model = new QSqlQueryModel();

    // Récupérer les données depuis la base de données
    Architecte A;
    model = A.afficher(); // Récupère les données depuis la méthode afficher() de votre classe Architecte

    // Définir le modèle dans QTableView
    ui->tableView->setModel(model);

   /* // Redimensionner les colonnes
    ui->tableView->resizeColumnsToContents();
    ui->tableView->horizontalHeader()->setStretchLastSection(true); */// Pour que la dernière colonne occupe tout l'espace restant
}

MainWindow::~MainWindow()
{
    delete ui;  // Libérer le pointeur ui
}

//-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

bool MainWindow::verifierMotDePasse(const QString &motDePasse)
{
    QRegularExpression regex("^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[^\w\\s]).{8,}$");
    QRegularExpressionMatch match = regex.match(motDePasse);

    QLabel *labelErreur = ui->labelErreur;

    if (match.hasMatch()) {
        labelErreur->setText("Mot de passe valide.");
        labelErreur->setStyleSheet("color: green;");
        return true;  // Mot de passe valide
    } else {
        labelErreur->setText("Mot de passe:Min.8 caractères,1majuscule,<br>1 minuscule,1 chiffre,1 spécial.");
        labelErreur->setStyleSheet("color: red;");

        labelErreur->setStyleSheet("color: red;");

        labelErreur->setStyleSheet("color: red;");
        return false; // Mot de passe invalide
    }
}

bool MainWindow::validateEmail(const QString &email)
{
    if (email.isEmpty()) {
        ui->labelEmailStatus->clear();
        return false;
    }

    QRegularExpression emailRegex("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");
    QRegularExpressionMatch match = emailRegex.match(email);

    if (match.hasMatch()) {
        ui->labelEmailStatus->setText("Email valide");
        ui->labelEmailStatus->setStyleSheet("color: green;");
        return true;  // Email valide
    } else {
        ui->labelEmailStatus->setText("Email invalide");
        ui->labelEmailStatus->setStyleSheet("color: red;");
        return false; // Email invalide
    }
}

bool MainWindow::verifierChampsLettresSeules(const QString &champ, QLabel *labelErreur)
{
    // Vérifier que la longueur du champ est d'au moins 3 caractères
    if (champ.length() < 3) {
        labelErreur->setText("Invalide:Min. 3 caractères");
        labelErreur->setStyleSheet("color: red;");
        return false; // Champ invalide
    }

    // Expression régulière pour vérifier que le champ contient uniquement des lettres (sans caractères spéciaux)
    QRegularExpression regex("^[A-Za-z]+$"); // Accepte seulement les lettres
    QRegularExpressionMatch match = regex.match(champ);

    if (match.hasMatch()) {
        labelErreur->setText("Valide");
        labelErreur->setStyleSheet("color: green;");
        return true; // Champ valide
    } else {
        labelErreur->setText("Invalide: uniquement des lettres.");
        labelErreur->setStyleSheet("color: red;");
        return false; // Champ invalide
    }
}


void MainWindow::setupValidation()
{
    // Connecter tous les champs à leur QLabel respectif pour la validation en temps réel
    connect(ui->lineEdit_nom, &QLineEdit::textChanged, this, [this]() {
        verifierChampsLettresSeules(ui->lineEdit_nom->text(), ui->labelNomErreur);
    });

    connect(ui->lineEdit_prenom, &QLineEdit::textChanged, this, [this]() {
        verifierChampsLettresSeules(ui->lineEdit_prenom->text(), ui->labelPrenomErreur);
    });

    connect(ui->lineEdit_role, &QLineEdit::textChanged, this, [this]() {
        verifierChampsLettresSeules(ui->lineEdit_role->text(), ui->labelRoleErreur);
    });

    connect(ui->lineEdit_response, &QLineEdit::textChanged, this, [this]() {
        verifierChampsLettresSeules(ui->lineEdit_response->text(), ui->labelReponseErreur);
    });
}

//----------------------CRUD---------------------------------------------------------------------------------------------------------------------------------------------------------------
void MainWindow::on_btnAjouter_clicked()
{
    int autoGeneratedID = generateAutoID();
    // Récupérer les informations de l'interface utilisateur
    QString nom = ui->lineEdit_nom->text();
    QString prenom = ui->lineEdit_prenom->text();
    QString role = ui->lineEdit_role->text();
    QString reponse = ui->lineEdit_response->text();
    QString question = ui->comboBox_question->currentText();

    // Récupérer le reste des informations et procéder aux autres vérifications (email, mot de passe, etc.)
    QString mail = ui->lineEdit_mail->text();
    QString motDePasse = ui->lineEdit_motDePasse->text();

    // Vérification si les champs sont vides
    if (nom.isEmpty() || prenom.isEmpty() || mail.isEmpty() || role.isEmpty() ||
        motDePasse.isEmpty() || reponse.isEmpty())
    {
        QMessageBox::warning(this, "Champs vides", "Tous les champs doivent être remplis !");
        return;
    }

    // Vérification de la validité des champs lettres seules
    if (!verifierChampsLettresSeules(nom, ui->labelNomErreur)) {
        QMessageBox::warning(this, "Nom invalide", "Le nom doit contenir uniquement des lettres.");
        return;
    }

    if (!verifierChampsLettresSeules(prenom, ui->labelPrenomErreur)) {
        QMessageBox::warning(this, "Prénom invalide", "Le prénom doit contenir uniquement des lettres.");
        return;
    }

    if (!verifierChampsLettresSeules(role, ui->labelRoleErreur)) {
        QMessageBox::warning(this, "Rôle invalide", "Le rôle doit contenir uniquement des lettres.");
        return;
    }

    if (!verifierChampsLettresSeules(reponse, ui->labelReponseErreur)) {
        QMessageBox::warning(this, "Réponse invalide", "La réponse doit contenir uniquement des lettres.");
        return;
    }

    // Vérification de l'email
    if (!validateEmail(mail)) {
        QMessageBox::warning(this, "Email invalide", "L'adresse e-mail saisie est invalide.\nVeuillez respecter le format standard de l'email.");
        return;
    }

    // Vérification du mot de passe
    if (!verifierMotDePasse(motDePasse)) {
        QMessageBox::warning(this, "Mot de passe invalide", "Le mot de passe doit respecter les critères");
        return;
    } else {
        motDePasse = hasherMotDePasse(motDePasse);
    }

    // Définir automatiquement les heures supplémentaires à 0
    int heuresSupplementaires = 0;

    // Créer l'objet Architecte avec les données
    Architecte A(autoGeneratedID, nom, prenom, mail, role, motDePasse, question, reponse, heuresSupplementaires);

    // Ajouter dans la base de données
    bool test = A.ajouter();
    if (test)
    {
        qDebug() << "Ajout réussi";

        // Rafraîchir les données après ajout
        Architecte Etmp;
        ui->tableView->setModel(Etmp.afficher());  // Mettre à jour le modèle de la table

        // Réinitialiser les champs après un ajout réussi
        on_annulerEvent_clicked();
    }
    else
    {
        qDebug() << "Erreur lors de l'ajout";
    }
}


QString MainWindow::hasherMotDePasse(const QString &motDePasse)
{
    QByteArray hash = QCryptographicHash::hash(motDePasse.toUtf8(), QCryptographicHash::Sha256);
    return hash.toBase64();  // Encodage en Base64
}



void MainWindow::on_annulerEvent_clicked()
{

    ui->lineEdit_nom->clear();
    ui->lineEdit_prenom->clear();
    ui->lineEdit_mail->clear();
    ui->lineEdit_role->clear();
    ui->lineEdit_motDePasse->clear();
    ui->lineEdit_response->clear();
 ui->labelErreur->clear();
    // Réinitialiser la combobox (si nécessaire)
    ui->comboBox_question->setCurrentIndex(0);  // Met la première valeur comme valeur par défaut
}

void MainWindow::on_btnsupprimer_clicked()
{
    // Récupérer l'ID à partir du champ de saisie
    int id = ui->lineEdit_IDS->text().toInt();

    // Créer une instance de la classe Architecte pour utiliser la méthode idExiste() et supprimer()
    Architecte Etmp;

    // Vérifier si l'ID existe dans la base de données avant de tenter de supprimer
    if (!Etmp.idExiste(id))  // Appeler la fonction idExiste pour vérifier l'existence de l'ID
    {
        // Si l'ID n'existe pas, afficher un message d'erreur et réinitialiser le champ de saisie
        QMessageBox::warning(this, "Erreur", "ID non trouvé !");
        ui->lineEdit_IDS->clear();  // Réinitialiser le champ de saisie de l'ID
        return;  // Sortir de la fonction sans effectuer la suppression
    }

    // Si l'ID existe, procéder à la suppression
    bool test = Etmp.supprimer(id);

    // Vérifier si la suppression a été réussie
    if (test)
    {
        // Si la suppression a réussi, afficher un message de succès dans la barre de débogage
        qDebug() << "Suppression effectuée avec succès!";

        // Rafraîchir les données dans la table après suppression
        QSqlQueryModel *model = Etmp.afficher();  // Mettre à jour le modèle de la table
        ui->tableView->setModel(model);  // Mettre à jour la vue du tableau avec les nouvelles données
    }
    else
    {
        // Si la suppression a échoué, afficher un message d'erreur dans la barre de débogage
        qDebug() << "Erreur: Suppression non effectuée.";
    }
}

// MainWindow.cpp

bool MainWindow::estTexteValide(const QString &texte)
{
    // Vérifier si la longueur du texte est d'au moins 3 caractères
    if (texte.length() < 3) {
        return false; // Le texte n'est pas valide
    }

    // Expression régulière pour vérifier si le texte contient uniquement des lettres (majuscule et minuscule)
    QRegularExpression regex("^[A-Za-z]+$");
    return regex.match(texte).hasMatch();
}


void MainWindow::modifierCellule(const QModelIndex &index)
{
    QSqlQueryModel *model = qobject_cast<QSqlQueryModel *>(ui->tableView->model());

    if (model) {
        // Si la colonne est en lecture seule (index 0 ou 7), ne pas permettre la modification
        if (index.column() == 0 || index.column() == 6 ||index.column() == 7 ||  index.column() == 8) {
            QMessageBox::warning(this, tr("Modification non autorisée"), tr("Vous ne pouvez pas modifier cette colonne."));
            return;
        }

        QString columnName = model->headerData(index.column(), Qt::Horizontal).toString();
        QString oldValue = model->data(index).toString();

        QString newValue = QInputDialog::getText(this, tr("Modifier la valeur"), tr("Nouvelle valeur :"), QLineEdit::Normal, oldValue);

        if (!newValue.isEmpty() && newValue != oldValue) {
            // Validation du nom de la colonne
            if (columnName.isEmpty() || !isValidColumn(columnName)) {
                QMessageBox::warning(this, tr("Erreur"), tr("Le nom de la colonne est invalide."));
                return;
            }

            // Si la colonne modifiée est "NBR_HEURES_SUPPLEMENTAIRES", valider que la valeur est un nombre
            if (columnName == "NBR_HEURES_SUPPLEMENTAIRES" && !isValidSupplementaryHours(newValue)) {
                QMessageBox::warning(this, tr("Erreur de saisie"), tr("Les heures supplémentaires doivent être un nombre valide."));
                return;
            }

            // Si la colonne est NOM, PRÉNOM ou RÔLE, valider que la valeur est un texte valide
            if ((columnName == "NOM" || columnName == "PRÉNOM" || columnName == "RÔLE") && !estTexteValide(newValue)) {
                QMessageBox::warning(this, tr("Erreur de saisie"), tr("Le champ doit contenir uniquement des lettres et un minimum de 3 caractères."));
                return;
            }

            // Récupération de l'ID de l'enregistrement à modifier
            int id = model->data(model->index(index.row(), 0)).toInt();

            // Appel de la fonction modifier de la classe Architecte pour mettre à jour la base de données
            Architecte etmp;
            bool success = etmp.modifier(id, columnName, newValue); // Appel à la méthode modifier

            if (success) {
                // Si la modification réussit, mettre à jour la cellule dans le modèle
                model->setData(index, newValue);
                // Rafraîchir les données après modification
                ui->tableView->setModel(etmp.afficher());  // Mettre à jour le modèle de la table
            } else {
                QMessageBox::warning(this, tr("Erreur de mise à jour"), tr("La mise à jour a échoué. Veuillez vérifier les données."));
            }
        }
    } else {
        qDebug() << "Le modèle n'est pas de type QSqlQueryModel.";
    }
}

// Fonction pour valider que la colonne est valide
bool MainWindow::isValidColumn(const QString &columnName)
{
    // Liste des colonnes valides
    QStringList validColumns = {"NOM", "PRÉNOM", "EMAIL","RÔLE","MOT_DE_PASSE","NBR_HEURES_SUPPLEMENTAIRES"}; // Remplace par les noms réels de tes colonnes

    return validColumns.contains(columnName);
}


bool MainWindow::isValidSupplementaryHours(const QString &value)
{
    bool isNumber;
    value.toInt(&isNumber);  // Vérifie si la chaîne peut être convertie en entier
    return isNumber;         // Retourne true si c'est un nombre, sinon false
}


